learning_templates/basic_app/urls.py
from  django.urls import path

from basic_app import views

app_name= 'basic_app'

urlpatterns = [
path('',views.index,name='index'),
path('other',views.other,name='other'),
path('register',views.register,name='register'),
path('relative',views.relative,name='relative'),
path('logout',views.user_logout,name="logout"),
path('special',views.special,name='special'),
path('login',views.user_login,name="login")
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns=[
    path('admin/', admin.site.urls),
    path('',include('basic_app.urls')),
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.
from  django.contrib.auth.models import User


class UserProfile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    portfolio_site=models.URLField(blank=True)
    profile_pic= models.ImageField(blank=True,upload_to='profile_pic')

    def __str__(self):
        return self.user.username

learning_templates/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfile



class UserForm(forms.ModelForm):
    
    password=forms.CharField(widget=forms.PasswordInput())


    class Meta():
        model=User
        fields=('username','email','password')

class UserProfileForm(forms.ModelForm):

    class Meta():
        model=UserProfile
        fields=('portfolio_site','profile_pic')

        

learning_templates/basic_app/views.py
from django.shortcuts import render,HttpResponse,reverse,redirect
from basic_app.forms import UserForm,UserProfileForm
from django.contrib.auth.decorators import login_required

from django.contrib.auth import authenticate,login,logout
# Create your views here.


def index(request):
    filters={'text':"Hello World",'number':100}
    return render(request,'basic_app/index.html',filters)


def other(request):
    return render(request,'basic_app/other.html')

def relative(request):
    return render(request,'basic_app/relative_url.html')


def register(request):

    registered=False
    
    if request.method =='POST':
        

        userform=UserForm(data=request.POST)
        userprofile=UserProfileForm(data=request.POST)
        print("heLooo daaa ithu",userform.is_valid(),"ithum noku",userprofile.is_valid())
        if userform.is_valid() and userprofile.is_valid():
           
            user=userform.save()
            user.set_password(user.password)
            user.save()

            profile=userprofile.save(commit=False)
            print("here")
            profile.user=user

            if 'profile_pic' in request.FILES:

                print("Found")
                profile.profile_pic=request.FILES['profile_pic']
            else:
                print("Not found")

            profile.save()
            registered=True
        else:
            print("errorrs daaa")
            print(userform.errors,userprofile.errors)

        


        
    else:
        userform=UserForm()
        userprofile=UserProfileForm()
        
    return render(request,'basic_app/registration.html',{'form1':userform,'form2':userprofile,'registered':registered})

def user_login(request):


    if request.method == 'POST':

        username=request.POST.get("username")
        password=request.POST.get("password")

        user=authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return redirect('/')
            else:
                return HttpResponse("User Not active")


        else:
            print("Somone tried login and filed")
            print("Username={} \n Password={}".format(username,password))
            return HttpResponse("Inavlid Credentials")

    else:
        return render(request,'basic_app/login.html')

@login_required
def special(request):

    return HttpResponse("You are logged in")



@login_required
def user_logout(request):

    logout(request)
    return redirect('/')

    

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <title>Document</title>
</head>
<body>

    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">

            <ul class="nav navbar-nav">
                
                <li><a class="navbar-brand" href="{% url 'basic_app:index' %}">INDEX</a></li>
                <li><a class="nav-link"  href="{% url 'admin:index' %}">Admin</a></li>
                <li><a  class="nav-link" href="{% url 'basic_app:register' %}">Register</a></li>

                {% if user.is_authenticated %}

                <li class="navbar-link"><a href="{% url 'basic_app:logout' %}">Log Out</a></li>

                {% else %}

                <li class="navbar-link"><a href="{% url 'basic_app:login' %}">Log In</a></li>
                
                {%  endif %}


            </ul>


        </div>


    </nav>
        <div class="container ">
    {% block body_block %}

    {% endblock %}
</div>
    
</body>
</html>

learning_templates/templates/basic_app/index.html
{% extends 'basic_app/base.html' %}

{% block body_block %}
<div class="container">
<div class="jumbotron">

    <h1>DJango Level One</h1>

</div>
</div>


{% endblock %}

learning_templates/templates/basic_app/login.html
{% extends 'basic_app/base.html' %}

{%  block body_block %}

<div class="jumbotron">

    <h1>Please Login</h1>
    <form action="{% url 'basic_app:login' %}" method="POST">

        {% csrf_token %}

        <label for="username">User Name:</label>
        <input type="text" name="username" placeholder="Ener user name">
        <label for="password">Password:</label>
        <input type="password" name="password" placeholder="password">

        <input type="submit" value="Login">

    </form>

</div>


{% endblock %}

learning_templates/templates/basic_app/other.html
{% extends "basic_app/base.html" %}
{% block body_block %}

   
    <h1>Welcome to Other</h1>
    <h2>This is an example of template inheritance</h2>
    <a href="{% url 'basic_app:index' %}">Go To index</a>


{% endblock %}

learning_templates/templates/basic_app/registration.html
{%extends 'basic_app/base.html' %}
{% load static %}
{% block body_block %}

<div class="jumbotron">

    {% if registered %}

    <h1>Registerd</h1>

    {% else %}
    <h1> Register Here </h1>

    <form method="post" enctype="multipart/form-data">

        {% csrf_token %}

        {{ form1.as_p }}

        {{ form2.as_p }}

        <input type="submit" name="" value="Register">

    </form>

    {% endif %}

</div>

{% endblock %}

learning_templates/templates/basic_app/relative_url.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Relative</title>
</head>
<body>
   
    <h1>Welcome to Relative Page</h1>

    <a href="{% url 'basic_app:other' %}">Go to Other</a> <br>

    <a href="{% url 'basic_app:index' %}">Go to index</a><br>
    <a href="{% url 'admin:index' %}">Go to admin</a>


</body>
</html>